task_view:
    path: /tasks
    controller: App\Controller\TaskController::index
task_create:
    path: /task/create
    controller: App\Controller\TaskController::create
task_user:
    path: /task/mis-tareas
    controller: App\Controller\TaskController::myTasks
task_edit:
    path: /task/edit/{id}
    controller: App\Controller\TaskController::edit
task_delete:
    path: /task/delete/{id}
    controller: App\Controller\TaskController::delete
task_detail:
    path: /task/{id}
    controller: App\Controller\TaskController::detail
users_view:
    path: /users
    controller: App\Controller\UserController::index
users_register:
    path: /users/register
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\UserController::login
logout:
    path: /logout
