index:
    path: /index
    controller: App\Controller\HomeController::index
animales:
    path: /animales/{nombre?}
    controller: App\Controller\HomeController::animales
    defaults: {nombre: 'Default'}
    methods: [GET]
    requirements:
      nombre: '[a-zA-Z]+'
redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir
animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index
animal_store:
    path: /animal/store
    controller: App\Controller\AnimalController::store
animal_detail:
    path: /animal/{id}
    controller: App\Controller\AnimalController::detail